apiVersion: v1
kind: Route
metadata:
  name: {{ include "revanchart.fullname" . }}
  labels:
    {{- include "revanchart.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ include "revanchart.fullname" . }}    