apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "revanchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "revanchart.selectorLabels" . | nindent 4 }}